#!/bin/bash
#Користувач має входити до наступних груп для керування: живленням, інтернетом, звуком, USB пристроями.

P=$(pwd)

echo "Enter user name:" &&
read user;

useradd -m -g wheel -G network,audio,video,cdrom,optical,scanner,users $user ;

echo "Enter password for your user:" ;
passwd $user ;

touch /etc/sudoers.d/$user &&
echo $user" ALL=(ALL) NOPASSWD: /usr/bin/halt, /usr/bin/poweroff, \
/usr/bin/reboot, /usr/bin/shutdown, /usr/bin/zzz, /usr/bin/ZZZ" >> /etc/sudoers.d/$user

echo FONT="UniCyr_8x16" >> /etc/rc.conf


xbps-install -Suy &&
xbps-install -Suvy zip unzip wayland wlroots sway xorg-fonts nano helix Waybar dbus elogind polkit rtkit wl-clipboard \
chrony alsa-utils pulseaudio telegram-desktop rofi foot python3 base-devel network-manager-applet pavucontrol \
ranger lxappearance bpytop wget curl pangox-compat brightnessctl xdg-user-dirs gnome-tweaks nemo &&

su $user -c /usr/bin/xdg-user-dirs-update &&

ln -s /etc/sv/dbus    /var/service  &&  
ln -s /etc/sv/elogind /var/service  &&
ln -s /etc/sv/polkitd /var/service  && 
ln -s /etc/sv/rtkit   /var/service  &&
ln -s /etc/sv/chrony  /var/service  &&
ln -s /etc/sv/alsa    /var/service  &&
ln -s /etc/sv/NetworkManager    /var/service  &&
rm /var/service/dhcpcd &&
cd /home/$user/ &&
cp -R $P/.backgrounds ./ &&
cp -R $P/.config      ./ && 
cp -R $P/.icons       ./ && 
cp    $P/.bashrc      ./ &&
mv $P/Dracula_themes/rofi/Dracula-Dark.rasi /usr/share/rofi/themes/ &&
chmod +x .config/sway/bin/* &&
#git clone https://github.com/void-linux/void-packages &&
git clone https://github.com/toluschr/xdeb.git && 
cd xdeb &&
chmod 0744 xdeb &&
wget https://download.onlyoffice.com/install/desktop/editors/linux/onlyoffice-desktopeditors_amd64.deb &&
wget https://download.anydesk.com/linux/deb/anydesk_5.5.6-1_amd64.deb &&
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
for deb_pkg in *.deb; do ./xdeb -Sde $deb_pkg; done &&
for xbps_pkg in $(ls binpkgs | grep xbps); do pkg=${xbps_pkg%.*.*}; xbps-install -y -R binpkgs $pkg; done &&
for dir in $(ls -d */); do rm -R $dir; done &&
rm *.deb &&
cd /home/$user/ &&
chown -R $user:wheel xdeb &&
#chown -R $user:wheel void-packages &&
chown -R $user:wheel .backgrounds &&
chown -R $user:wheel .config &&
chown -R $user:wheel .icons &&
chown $user:wheel .bashrc &&
#cd void-packages && 
#echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf &&
#su $user ./xbps-src binary-bootstrap &&
#su $user ./xbps-src pkg google-chrome && 
#su $user ./xbps-src pkg brightnessctl &&
#xbps-install -y --repository=/home/$user/void-packages/hostdir/binpkgs/nonfree google-chrome &&
#xbps-install -y --repository=/home/$user/void-packages/hostdir/binpkgs/ brightnessctl &&
#cd .. &&
git clone https://github.com/m4thewz/dracula-icons.git /usr/share/icons/dracula-icons &&
git clone https://github.com/dracula/gtk.git /usr/share/themes/Dracula &&
git clone https://github.com/FortAwesome/Font-Awesome &&
cd Font-Awesome && 
install  -Dm644 otfs/*.otf -t /usr/share/fonts/OTF &&
cd .. &&
rm -R Font-Awesome &&
rm -R $P && 
reboot
