#!/bin/bash
#Користувач має входити до наступних груп для керування: живленням, інтернетом, звуком, USB пристроями.
xbps-install zip unzip wayland wlroots sway xorg-fonts nano neovim Waybar dbus elogind polkit rtkit \
chrony alsa-utils pulseaudio telegram-desktop dmenu &&
ln -s /etc/sv/dbus    /var/service  &&  
ln -s /etc/sv/elogind /var/service  &&
ln -s /etc/sv/polkitd /var/service  && 
ln -s /etc/sv/rtkit   /var/service  &&
ln -s /etc/sv/chrony  /var/service  &&
ln -s /etc/sv/alsa    /var/service  &&
useradd -m -g wheel -G audio,video,cdrom,optical,scanner,plugdev,users void && 
passwd void &&
cd /home/void/ &&
git clone https://github.com/void-linux/void-packages &&
chown -R void:wheel void-packages &&
cd void-packages && 
./xbps-src pkg google-chrome && 
xbps-install --repository=/home/void/void-packages/hostdir/binpkgs/nonfree google-chrome &&
rm -R /root/void_install && 
reboot
