#!/bin/bash
#Користувач має входити до наступних груп для керування: живленням, інтернетом, звуком, USB пристроями.

echo "Enter user name:" &&
read user &&

useradd -m -g wheel -G network,audio,video,cdrom,optical,scanner,plugdev,users $user && 

echo "Enter password for your user:" &&
passwd $user &&

touch /etc/sudoers.d/$user &&
echo $user" ALL=(ALL) NOPASSWD: /usr/bin/halt, /usr/bin/poweroff, \
/usr/bin/reboot, /usr/bin/shutdown, /usr/bin/zzz, /usr/bin/ZZZ" >> /etc/sudoers.d/$user

xbps-install -Suvy zip unzip wayland wlroots sway xorg-fonts nano helix Waybar dbus elogind polkit rtkit wl-clipboard \
chrony alsa-utils pulseaudio telegram-desktop dmenu foot python3 base-devel NetworkManager pavucontrol &&
ln -s /etc/sv/dbus    /var/service  &&  
ln -s /etc/sv/elogind /var/service  &&
ln -s /etc/sv/polkitd /var/service  && 
ln -s /etc/sv/rtkit   /var/service  &&
ln -s /etc/sv/chrony  /var/service  &&
ln -s /etc/sv/alsa    /var/service  &&
ln -s /etc/sv/NetworkManager    /var/service  &&
rm /var/service/dhcpd &&
cd /home/void/ &&
cp -R /root/void_install/.backgrounds ./ &&
cp -R /root/void_install/.config      ./ && 
cp  /root/void_install/.bashrc        ./ &&
git clone https://github.com/void-linux/void-packages &&
chown -R void:wheel void-packages &&
chown -R void:wheel .backgrounds &&
chown -R void:wheel .config &&
cd void-packages && 
echo XBPS_ALLOW_RESTRICTED=yes >> etc/conf &&
su void ./xbps-src binary-bootstrap &&
su void ./xbps-src pkg google-chrome && 
xbps-install -y --repository=/home/void/void-packages/hostdir/binpkgs/nonfree google-chrome &&
cd .. &&
git clone https://github.com/FortAwesome/Font-Awesome &&
cd Font-Awesome && 
install  -Dm644 otfs/*.otf -t /usr/share/fonts/OTF &&
cd .. &&
rm -R Font-Awesome &&
rm -R /root/void_install && 
reboot
